language: php
sudo: required
php:
  - 5.5
addons:
  hosts:
    - local.courseadvisor.ch
install:
  - npm install
  - npm install -g casperjs jasmine-node
before_script:
  - hostname
  - gulp publish
  - php artisan serve --port=8080 --host 0.0.0.0 &
  - ./test.sh --seed --setup-margarita
script:
  - ./test.sh -m -p 8080
