language: php
sudo: required
php:
  - 5.5
addons:
  hosts:
    - local.courseadvisor.ch
before_install:
  - mysql -e "create database IF NOT EXISTS courseadvisor;" -uroot
  - cat ./app/database/seeds/testing.sql | mysql -uroot
install:
  - npm install
  - npm install -g casperjs jasmine-node
before_script:
  - gulp publish
  - php artisan serve --port=9000 --host=local.courseadvisor.ch >/dev/null 2>&1 &
  - sleep 3
script:
  - node ultimate-debug.js
  - ./test.sh -p 9000
