language: php
sudo: required
php:
  - 5.5
addons:
  hosts:
    - local.courseadvisor.ch
before_install:
  - mysql -e "create database IF NOT EXISTS courseadvisor;" -uroot
  - cat ./app/database/seeds/testing.sql | mysql -uroot
install:
  - npm install
  - npm install -g casperjs
before_script:
  - gulp publish
  - php artisan serve --port=8080 --host=local.courseadvisor.ch &
script:
  - casperjs test tests/travis-config.coffee tests/test-*